# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'appWithRedux' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for appWithRedux
  pod 'AdyenCSE'

  target 'appWithRedux-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appWithReduxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
 